export const ES = 10; // erase size
export const ES2 = ES / 2;
export const BS = 5; // brush size
export const EH = Math.ceil(ES / Math.sqrt(2));
export const CHUNK_TIME = 500;
export const CHUNK_SIZE_TRIGGER = 64;
export const ERASE_SIZE_TRIGGER = 8;
export const TAIL_SIZE = 500;
export const MAX_CANVAS_SIZE = 2048;
